--- #YAML:1.0
name:                   Data-Phrasebook-Loader-JSON
version:                0.01
abstract:               Loader class for phrasebook implementations using JSON files
author:
  - Barbie <barbie@cpan.org>

license:                  artistic_2
distribution_type:        module
installdirs:              site

requires:
  perl:                   5.006
  Carp:                   0
  Data::Phrasebook:       0.24
  File::Slurp:            0
  JSON::XS:               0
recommends:
  Test::CPAN::Meta:       0
  Test::CPAN::Meta::JSON: 0
  Test::Distribution:     0
  Test::Pod:              1.00
  Test::Pod::Coverage:    0.08
build_requires:
  IO::File:               0
  Test::More:             0.70

provides:
  Data::Phrasebook::Loader::JSON:
    file: lib/Data/Phrasebook/Loader/JSON.pm
    version: 0.01

no_index:
  directory:
    - t
    - examples

resources:
  license:    http://www.perlfoundation.org/artistic_license_2_0
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Data-Phrasebook-Loader-JSON
  repository: git://github.com/barbie/data-phrasebook-loader-json.git

meta-spec:
   version:   1.3
   url:       http://module-build.sourceforge.net/META-spec-v1.3.html
generated_by: Hand 1.0
